apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway-monitor
  namespace: monitoring
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      app: pushgateway
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: web
      interval: 5s